name: Debug SSH Connection

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test basic connectivity
      run: |
        echo "🔍 Тестируем базовое подключение..."
        echo "Host: ${{ secrets.SERVER_HOST }}"
        echo "Port: ${{ secrets.SERVER_PORT }}"
        
        # Ping test
        ping -c 3 ${{ secrets.SERVER_HOST }} || echo "❌ Ping failed"
        
        # Telnet test
        timeout 10 telnet ${{ secrets.SERVER_HOST }} ${{ secrets.SERVER_PORT }} || echo "❌ Telnet failed"
        
    - name: Test SSH with different options
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 60s
        command_timeout: 2m
        debug: true
        use_insecure_cipher: true
        cipher: "aes128-ctr"
        script: |
          echo "✅ SSH подключение работает!"
          echo "Сервер: $(hostname)"
          echo "Пользователь: $(whoami)"
          echo "SSH версия: $(ssh -V 2>&1)"
          echo "OpenSSH версия: $(ssh -V 2>&1 | grep -o 'OpenSSH_[0-9.]*')"
