name: Deploy to Local Server (Fixed)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check local environment
      run: |
        echo "=== Local Environment Check ==="
        echo "Date: $(date)"
        echo "Uptime: $(uptime)"
        echo "Docker version: $(docker --version)"
        echo "Docker Compose version: $(docker compose version)"
        echo "Available disk space:"
        df -h
        echo "Memory usage:"
        free -h
        echo "Running containers:"
        docker ps -a
        echo "=== Local Environment Check Completed ==="
        
    - name: Clean up old containers and images
      run: |
        echo "=== Cleaning up old containers and images ==="
        
        # Остановка и удаление старых контейнеров через docker-compose
        echo "Stopping and removing old containers..."
        docker compose down -v --remove-orphans || true
        
        # Удаление старых образов приложения
        echo "Removing old application images..."
        docker rmi university-app:latest || true
        
        # Очистка неиспользуемых образов и контейнеров
        echo "Cleaning up unused Docker resources..."
        docker system prune -f
        
        # Показать освобожденное место
        echo "Docker system usage after cleanup:"
        docker system df
        
        echo "=== Cleanup completed ==="
        
    - name: Build and deploy application with docker-compose
      run: |
        echo "=== Building and deploying application with docker-compose ==="
        
        # Сборка и запуск через docker-compose
        echo "Building and starting services..."
        docker compose up -d --build
        
        # Ожидание готовности сервисов
        echo "Waiting for services to be ready..."
        sleep 30
        
        # Проверка статуса сервисов
        echo "=== Service Status ==="
        docker compose ps
        
        # Проверка healthcheck статуса
        echo "=== Health Check Status ==="
        docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
        
        echo "=== Service Logs ==="
        echo "PostgreSQL logs:"
        docker compose logs postgres --tail 10
        echo "MongoDB logs:"
        docker compose logs mongodb --tail 10
        echo "App logs:"
        docker compose logs app --tail 10
        
    - name: Verify deployment
      run: |
        echo "=== Verifying deployment ==="
        
        # Проверка статуса всех контейнеров
        echo "=== Container Status ==="
        docker compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
        
        # Проверка PostgreSQL
        echo "=== PostgreSQL Check ==="
        if docker compose exec -T postgres pg_isready -U postgres -d university; then
          echo "✅ PostgreSQL работает корректно"
        else
          echo "❌ PostgreSQL не отвечает"
          docker compose logs postgres --tail 20
        fi
        
        # Проверка MongoDB
        echo "=== MongoDB Check ==="
        if docker compose exec -T mongodb mongosh --eval "print('MongoDB test')" > /dev/null 2>&1; then
          echo "✅ MongoDB работает корректно"
        else
          echo "❌ MongoDB не отвечает"
          docker compose logs mongodb --tail 20
        fi
        
        # Проверка приложения
        echo "=== Application Check ==="
        echo "Testing application endpoint..."
        sleep 10
        
        # Диагностика сетевых настроек
        echo "=== Network Diagnostics ==="
        echo "Checking ports:"
        ss -tlnp | grep :8080 || echo "Port 8080 not listening"
        echo "Docker port mapping:"
        docker compose port app 8080 || echo "Container port not mapped"
        echo "Machine IP:"
        hostname -I
        echo "Firewall status:"
        ufw status 2>/dev/null || echo "ufw not installed or inactive"
        
        # Попытка открыть порт в firewall
        echo "Opening port 8080 in firewall..."
        ufw allow 8080 2>/dev/null || echo "Could not open port (may already be open)"
        
        # Тестирование приложения
        if curl -f http://localhost:8080/ > /dev/null 2>&1; then
          echo "✅ Application responds on http://localhost:8080/"
          echo "🌐 Available addresses:"
          echo "   - http://localhost:8080"
          echo "   - http://$(hostname -I | awk '{print $1}'):8080"
        else
          echo "❌ Application does not respond on localhost:8080"
          echo "Trying 0.0.0.0:8080..."
          if curl -f http://0.0.0.0:8080/ > /dev/null 2>&1; then
            echo "✅ Application responds on 0.0.0.0:8080"
          else
            echo "❌ Application does not respond"
            echo "Application logs:"
            docker compose logs app --tail 20
          fi
        fi
        
        echo "=== Deployment verification completed ==="
